### ISSUE TITLE
Meetup 2017/05/03

### ISSUE THREAD

**Issue by fitzgen** [pdxrust/meetups#1]
# Meetup 2017/05/03

* [x] Speaker: @carllerche I think?

* [x] Title: something about futures / tokio I think?

* [x] Abstract: `_____________`

* [x] Location: Mozilla (but I still need to make the calendar reservation thing)

* [X] Time: 6pm

* [X] On-site host: @fitzgen

* [x] Announce on https://www.meetup.com/PDXRust/

CC organizers: @benstreb @edunham @fitzgen @jameysharp @jeenalee @jimblandy @MDCox @wraithan

**Comment by edunham** [comment]
I already booked the room, though June needs to be booked. Got an abstract thingy from Carl, put it on Meetup, mirrored Meetup to Calagator through the magic Calagator button. 

Remaining work: Print attendee list on day of meeting and give it to Katt; have meetup.
